spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        show-sql: false
    defer-datasource-initialization: true

  datasource:
    url: jdbc:postgresql://localhost:5433/drone_test
    username: postgres
    password: r00t34d0r.
    driver-class-name: org.postgresql.Driver

server:
  port: 8081
